deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: dist
  on:
    branch: master
language: node_js
node_js:
  - "7"
install:
    - npm install
    - npm run build
