deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: build
  on:
    branch: master
language: node_js
node_js:
  - "14"
install:
  - yarn install --pure-lockfile
before_script:
  - yarn test
script:
  - yarn build
