version: '3.7'

services:
  app:
    container_name: coxinha-calculator
    stdin_open: true
    build:
      context: .
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - SASS_PATH=node_modules:src
